'use strict';

module.exports = Object.freeze({
  util: require('util'),
  path: require('path'),
  buffer: require('buffer'),
  os: require('os'),
  v8: require('v8'),
  vm: require('vm'),
  'child_process': require('child_process'),
  'worker_threads': require('worker_threads'),
  stream: require('stream'),
  fs: require('fs'),
  fsp: require('fs/promises'),
  crypto: require('crypto'),
  zlib: require('zlib'),
  readline: require('readline'),
  'async_hooks': require('async_hooks'),
  timers: { ...require('timers'), promises: require('timers/promises') },
  events: require('events'),
  dns: require('dns'),
  net: require('net'),
  tls: require('tls'),
  http: require('http'),
  https: require('https'),
  http2: require('http2'),
  dgram: require('dgram'),
  process,
});
